// Copyright (c) 2024-2026 Lux Industries Inc.
// SPDX-License-Identifier: BSD-3-Clause-Eco
//
// EVM 256-bit modular arithmetic spec-vector integration test.
//
// Vectors generated by Python `(a * b) % m` and `(a + b) % m` over canonical
// 256-bit unsigned integers. The luxcpp body documents that when m == 0 the
// C-ABI returns CRYPTO_ERR_INPUT (the caller is expected to map zero-modulus
// to a zero result before calling, matching EVM precompile dispatch
// behavior).

use lux_crypto_evm256::{addmod, mulmod, WORD_LEN};

fn from_hex(s: &str) -> [u8; WORD_LEN] {
    let s = s.as_bytes();
    assert_eq!(s.len(), 2 * WORD_LEN);
    let mut out = [0u8; WORD_LEN];
    let nibble = |c: u8| -> u8 {
        match c {
            b'0'..=b'9' => c - b'0',
            b'a'..=b'f' => c - b'a' + 10,
            b'A'..=b'F' => c - b'A' + 10,
            _ => panic!("non-hex"),
        }
    };
    for i in 0..WORD_LEN {
        out[i] = (nibble(s[2 * i]) << 4) | nibble(s[2 * i + 1]);
    }
    out
}

struct V {
    name: &'static str,
    a: &'static str,
    b: &'static str,
    m: &'static str,
    mul: &'static str,
    add: &'static str,
}

const VECTORS: &[V] = &[
    V {
        name: "two_three_seven",
        a: "0000000000000000000000000000000000000000000000000000000000000002",
        b: "0000000000000000000000000000000000000000000000000000000000000003",
        m: "0000000000000000000000000000000000000000000000000000000000000007",
        mul: "0000000000000000000000000000000000000000000000000000000000000006",
        add: "0000000000000000000000000000000000000000000000000000000000000005",
    },
    V {
        name: "max_minus_one_mod_max",
        a: "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
        b: "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
        m: "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
        mul: "0000000000000000000000000000000000000000000000000000000000000000",
        add: "0000000000000000000000000000000000000000000000000000000000000000",
    },
    V {
        name: "max_minus_one_mod_secp_n",
        a: "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
        b: "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
        m: "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141",
        mul: "9d671cd581c69bc5e697f5e45bcd07c3e972508f6d0e38f00911af2e084453c3",
        add: "000000000000000000000000000000028aa24632a16ebf88805b42e65f937d7c",
    },
    V {
        name: "max_one_mod_p_bls12_381",
        a: "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
        b: "0000000000000000000000000000000000000000000000000000000000000001",
        m: "73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001",
        mul: "1824b159acc5056f998c4fefecbc4ff55884b7fa0003480200000001fffffffd",
        add: "1824b159acc5056f998c4fefecbc4ff55884b7fa0003480200000001fffffffe",
    },
    V {
        name: "five_seven_eleven",
        a: "0000000000000000000000000000000000000000000000000000000000000005",
        b: "0000000000000000000000000000000000000000000000000000000000000007",
        m: "000000000000000000000000000000000000000000000000000000000000000b",
        mul: "0000000000000000000000000000000000000000000000000000000000000002",
        add: "0000000000000000000000000000000000000000000000000000000000000001",
    },
    V {
        name: "one_one_two",
        a: "0000000000000000000000000000000000000000000000000000000000000001",
        b: "0000000000000000000000000000000000000000000000000000000000000001",
        m: "0000000000000000000000000000000000000000000000000000000000000002",
        mul: "0000000000000000000000000000000000000000000000000000000000000001",
        add: "0000000000000000000000000000000000000000000000000000000000000000",
    },
    V {
        name: "one_two_two",
        a: "0000000000000000000000000000000000000000000000000000000000000001",
        b: "0000000000000000000000000000000000000000000000000000000000000002",
        m: "0000000000000000000000000000000000000000000000000000000000000002",
        mul: "0000000000000000000000000000000000000000000000000000000000000000",
        add: "0000000000000000000000000000000000000000000000000000000000000001",
    },
    V {
        name: "thirteen_seventeen_seven",
        a: "000000000000000000000000000000000000000000000000000000000000000d",
        b: "0000000000000000000000000000000000000000000000000000000000000011",
        m: "0000000000000000000000000000000000000000000000000000000000000007",
        mul: "0000000000000000000000000000000000000000000000000000000000000004",
        add: "0000000000000000000000000000000000000000000000000000000000000002",
    },
    V {
        name: "max_minus_two_squared_mod_max",
        a: "fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe",
        b: "fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe",
        m: "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
        mul: "0000000000000000000000000000000000000000000000000000000000000001",
        add: "fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd",
    },
    V {
        name: "p_bls_minus_one_squared_mod_p_bls",
        a: "73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000000",
        b: "73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000000",
        m: "73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001",
        mul: "0000000000000000000000000000000000000000000000000000000000000001",
        add: "73eda753299d7d483339d80809a1d80553bda402fffe5bfefffffffeffffffff",
    },
];

#[test]
fn published_vectors_byte_equal() {
    for v in VECTORS {
        let a = from_hex(v.a);
        let b = from_hex(v.b);
        let m = from_hex(v.m);
        let want_mul = from_hex(v.mul);
        let want_add = from_hex(v.add);
        let got_mul = mulmod(&a, &b, &m).unwrap_or_else(|e| panic!("{}: mulmod {:?}", v.name, e));
        let got_add = addmod(&a, &b, &m).unwrap_or_else(|e| panic!("{}: addmod {:?}", v.name, e));
        assert_eq!(got_mul, want_mul, "{}: mulmod mismatch", v.name);
        assert_eq!(got_add, want_add, "{}: addmod mismatch", v.name);
    }
}

#[test]
fn word_len_constant() {
    assert_eq!(WORD_LEN, 32);
}

#[test]
fn zero_modulus_returns_bad_input() {
    let zero = [0u8; WORD_LEN];
    let one = {
        let mut o = [0u8; WORD_LEN];
        o[31] = 1;
        o
    };
    assert!(mulmod(&one, &one, &zero).is_err());
    assert!(addmod(&one, &one, &zero).is_err());
}

#[test]
fn deterministic_repeated_calls() {
    let a = from_hex("0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20");
    let b = from_hex("2122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f40");
    let m = from_hex("73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001");
    let r1 = mulmod(&a, &b, &m).unwrap();
    let r2 = mulmod(&a, &b, &m).unwrap();
    assert_eq!(r1, r2);
}
