name: Crypto Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'crypto/**'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'crypto/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24.x']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache: true
        cache-dependency-path: crypto/go.sum
    
    - name: Install dependencies
      run: |
        cd crypto
        go mod download
    
    - name: Run tests
      run: |
        cd crypto
        go test -v -short -coverprofile=coverage.out -covermode=atomic ./...
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./crypto/coverage.out
        flags: crypto
        name: crypto-coverage
